config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :stories
  root'pages#index'

end

app/models/story.rb
class Story < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :stories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def index
    end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
    before_action :authenticate_user!
    before_action :find_story, only: [:edit, :update, :destroy]
    def new
        @story = current_user.stories.new
    end

    def index
        @stories = current_user.stories.order(created_at: :desc)
    end

    def create
        @story = current_user.stories.new(story_params)
        if @story.save
            redirect_to stories_path, notice: '新增成功'            
        else
            render :new
        end
    end

    def edit
        
    end

    def update
      if @story.update(story_params)
        redirect_to stories_path, notice: '文章更新成功'
      else
        render :edit
      end
    end

    def destroy
      @story.destroy
      redirect_to stories_path, notice: '文章刪除成功！'  
    end

    private
    def find_story
        @story = current_user.stories.find(params[:id])
    end
    def story_params
        params.require(:story).permit(:title, :content)
    end
end

app/helpers/storied_helper.rb
module StoriedHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyMedium</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render'/shared/frontend/navbar'%>
    <div class="container" >
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/frontend/_navbar.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
      <%= link_to root_path, class: 'navbar-item' do%>
        <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28">
        <% end %>
  
      <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>
  
    <div id="navbarBasicExample" class="navbar-menu">
      <div class="navbar-start">  
      </div>
  
      <div class="navbar-end">
        <div class="navbar-item">
          <div class="buttons">
          <% if user_signed_in? %>
            <div class="navbar-item has-dropdown is-hoverable">
                <a class="navbar-link">
                  <%= current_user.email%>
                </a>

                <div class="navbar-dropdown">                          
                    <%= link_to "新增文章", new_story_path, class: 'navbar-item'%>
                    <%= link_to "所有文章", stories_path, class: 'navbar-item'%>
                   <%= link_to "個人資料", edit_user_registration_path, class: 'navbar-item' %>          
                  <hr class="navbar-divider">
                    <%= link_to "登出", destroy_user_session_path, method: 'delete', class: 'navbar-item', data: {confirm: '是否確定登出？'} %> 
                </div>
          </div>
          <% else %>
            <%= link_to "註冊", new_user_registration_path, class: 'button is-primary' %>
            <%= link_to "登入", new_user_session_path, class: 'button is-light' %>
          <% end %>
            
          </div>
        </div>
      </div>
    </div>
  </nav>

app/views/stories/_form.html.erb
<%= form_for(story) do |form|%>
        <div class="field">
            <%= form.label :title, '標題' %>
            <%= form.text_field :title , class: 'input is-success'%>
        </div>

        <div class="field">
            <%= form.label :content, '內文' %>
            <%= form.text_area :content, rows: 10, class: 'textarea is-success'%>
        </div>

        <div class="field">
            <%= form.submit '儲存草稿', class: 'button is-light'%>
            <%= form.submit '發佈文章', class: 'button is-success'%>
        </div>

<% end %>

app/views/stories/edit.html.erb
<h1 class="title"> 編輯文章</h1>
<%= render 'form', story: @story %>

app/views/stories/index.html.erb
<%= notice%>
<h1 class="title">文章列表</h1>
<% @stories.each do |story|%>
<div class="content">
    <h2 class="title"><%= story.title %></h2>
    <p><%= story.content%></p>
    <p>
        最後編輯時間：<%= time_ago_in_words(story.updated_at) %>
        <%= link_to "編輯", edit_story_path(story), class: 'button is-text is-small'%>
        <%= link_to "刪除", story, method: 'delete', class: 'button is-danger is-small', data: { confirm: '確認刪除？'}%>
    </p>
    <hr>
</div>
<% end %>

app/views/stories/new.html.erb
<h1 class="title">新增文章</h1>
<%= render 'form', story: @story %>