Desktop/ruby_tix-dev/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, 
             :controllers => {
               :registrations => "users/registrations", 
               :omniauth_callbacks => "users/omniauth_callbacks"
             }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :pages do
    # 沒id
    collection do
      get :search
      get :footer_page
    end
  end 


  resources :activities
  root to: 'pages#index'

  resources :orders, only:[:index, :show, :create, :destroy]

  resource :cart, only:[:index, :destroy] do
    collection do
      post :add, path:'add/:id'
    end
  end

  resources :activities, only:[] do
    # 主辦方設定票券寫在activity new 頁面 暫定
    resources :ticket_types, :except => [ :show]
    get "/ticket_types/choose_ticket", to: "ticket_types#choose_ticket"

    # 單一活動底下 comment
    resources :comments, only:[:new, :create, :delete]
  end

  #使用者選則票券頁面
  resources :ticket_types, only:[ :choose_ticket]
  # 訂單成立後顯示個人票券
  resources :tickets, only: [:show]
  
end

Desktop/ruby_tix-dev/app/models/activity.rb
class Activity < ApplicationRecord
  has_many :users, through: :activity_users 
  has_many :activity_users
  has_many :comments
  has_many :tickets

  # ticket_type 寫在activity頁面 巢狀表單
  has_many :ticket_types, dependent: :destroy
  accepts_nested_attributes_for :ticket_types, allow_destroy: true

end

Desktop/ruby_tix-dev/app/models/activity_user.rb
class ActivityUser < ApplicationRecord
  belongs_to :user
  belongs_to :activity
end

Desktop/ruby_tix-dev/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Desktop/ruby_tix-dev/app/models/cart.rb
class Cart

end

Desktop/ruby_tix-dev/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :activity
  validates :content, presence: true
end

Desktop/ruby_tix-dev/app/models/order.rb
class Order < ApplicationRecord
  include AASM
  
  aasm column: :state do
    state :pending, initial: true
    state :paid, :refund, :completed

    event :pay do
      transitions from: :pending, to: :paid
      after do
        # 寄發email，已支付款項
      end
    end

    event :refund do
      transitions from: :paid, to: :refunded

      after do
        # 寄發email，已完成退款
      end
    end

    event :compelte do
      transitions from: :paid, to: :completed
    end
  end

end

Desktop/ruby_tix-dev/app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :ticket_type
  belongs_to :order
end

Desktop/ruby_tix-dev/app/models/ticket_type.rb
class TicketType < ApplicationRecord
  validates :price, :title, :quantity, presence: true
  
  belongs_to :activity
  has_many :tickets
end

Desktop/ruby_tix-dev/app/models/user.rb
class User < ApplicationRecord
  has_many :activities, through: :activity_users
  has_many :activity_users
  has_many :comments

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook, :google_oauth2]

  has_rich_text :content



  def self.from_omniauth(auth)
     # Case 1: Find existing user by facebook uid
     user = User.find_by_fb_uid( auth.uid )
     if user
        user.fb_token = auth.credentials.token
        #user.fb_raw_data = auth
        user.save!
       return user
     end

     # Case 2: Find existing user by email
     existing_user = User.find_by_email( auth.info.email )
     if existing_user
       existing_user.fb_uid = auth.uid
       existing_user.fb_token = auth.credentials.token
       #existing_user.fb_raw_data = auth
       existing_user.save!
       return existing_user
     end

     # Case 3: Create new password
     user = User.new
     user.fb_uid = auth.uid
     user.fb_token = auth.credentials.token
     user.email = auth.info.email
     user.password = Devise.friendly_token[0,20]
     #user.fb_raw_data = auth
     user.save!
     return user
   end




  # where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
  #   user.email = auth.info.email
  #   user.password = Devise.friendly_token[0, 20]
  #   # user.name = auth.info.name
  #   # user.avatar = auth.info.image
  #   # If you are using confirmable and the provider(s) you use validate emails, 
  #   # uncomment the line below to skip the confirmation emails.
  #   # user.skip_confirmation!
  # end
  
end

Desktop/ruby_tix-dev/app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def index
    @activities = Activity.all
  end

  def new
    @activity = Activity.new
    2.times { @activity.ticket_types.build }
  end

  def edit
    @activity= Activity.find(params[:id])
  end

  def update
    @activity= Activity.find(params[:id])
    
    if @activity.update(activity_params)
      redirect_to activity_ticket_types_path(@activity)      
    else
      render :edit
    end
  end

  def create
    @activity = Activity.new(activity_params)
    if @activity.save
      redirect_to activity_ticket_types_path(@activity.id)
    else
      
    end
  end

  def show
    @activity = Activity.find(params[:id])
    @comment= @activity.comments.new
    @comments = @story.comments.order(id: :desc)
  end


  private
  def activity_params
    params.require(:activity).permit(:begin_datetime, :finish_datetime, ticket_types_attributes: [:id, :title, :content, :quantity, :sell_start, :sell_deadline,:price, :_destroy])
  end
end

Desktop/ruby_tix-dev/app/controllers/carts_controller.rb
class CartsController < ApplicationController
end

Desktop/ruby_tix-dev/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  acts_as_paranoid without_default_scope: true

  def create
    @activity = Avtivity.find(parmas[:id])  
    @comment = @activity.comments.create(comment_params)  
  end

  private
  def comment_params
    params.require(:comment).permit(:content)
  end
end

Desktop/ruby_tix-dev/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  
end

Desktop/ruby_tix-dev/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # before_action :authenticate_user!
  def index
  end

  def footer_page
  end

  def search
    p params[:search]
    # ILIKE & LIKE
    # limit(2) -> 搜尋前兩個
    @search_value = User.where('email ILIKE ?', "%#{params[:search]}%").limit(2)
    respond_to do |format|
      format.json {render json: @search_value}
    end
  end
end

Desktop/ruby_tix-dev/app/controllers/ticket_types_controller.rb
class TicketTypesController < ApplicationController
  
  def choose_ticket
    @activity = Activity.find(params[:activity_id])
    @ticket_types = @activity.ticket_types
  end

  def index
    @activity = Activity.find(params[:activity_id])
    @ticket_types = @activity.ticket_types.order(updated_at: :desc)
  end

  def destroy
    @ticket_types = TicketType.find_by(id: params[:id])
    @ticket_types.destroy
    redirect_to activity_ticket_types_path
  end





end

Desktop/ruby_tix-dev/app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  
  # 顯示使用者票券
  def show
    @ticket = Ticket.find(params[:id])
    owner_id = @ticket.order.user_id
    @ticket_owner= User.find(owner_id)
  end
end

Desktop/ruby_tix-dev/app/controllers/users_controller.rb
class UsersController < Devise::RegistrationsController

  def index
    redirect_to root_path
  end
end

Desktop/ruby_tix-dev/app/helpers/activities_helper.rb
module ActivitiesHelper
end

Desktop/ruby_tix-dev/app/helpers/admin/ticket_types_helper.rb
module Admin::TicketTypesHelper
end

Desktop/ruby_tix-dev/app/helpers/application_helper.rb
module ApplicationHelper
end

Desktop/ruby_tix-dev/app/helpers/comments_helper.rb
module CommentsHelper
end

Desktop/ruby_tix-dev/app/helpers/pages_helper.rb
module PagesHelper
end

Desktop/ruby_tix-dev/app/views/ticket_types/choose_ticket.html.erb
<h1>請選擇票券</h1>

<% @ticket_types.each do |ticket| %>  
  <div class="card choose-ticket-card" id="accordion">
    <div class="card-body price" >
      <h5 class="card-title"><%= ticket.title %></h5>
      <h6 class="card-subtitle mb-2 text-muted">NT$<%= ticket.price %></h6>

      <a class="card-link" data-toggle="collapse" data-parent="#accordion" href="#collapse`${ticket_types.id}`"  data-target="#e" >更多資訊</a>
      <div class="qty " style="display:inline; margin-left:250px;">
        <span class="minus"style="margin-right:20px;"> <a href="#"><i class="fas fa-minus-circle"></i></a></span>
        <input type="number" class="count" name="qty" value="1" style="width: 30px;">
        <span class="plus "> <a href="#"><i class="fas fa-plus-circle"></i></a></span>
      </div>
     
      

              
    </div>

    <div class="collapse " id="e" >
      <div class="card card-body info" >
        <h2>活動資訊：</h2>
        <%= ticket.content %>
      </div>
    </div>

  </div>
<% end %>

<script>
  $('.collapse').collapse('toggle')
</script>  
  




  

Desktop/ruby_tix-dev/app/views/ticket_types/index.html.erb
<h1 class="title">票券列表</h1>

<table class="table table-hover">
  <thead class="table-dark">
    <tr>
      <th>活動id</th>
      <th>活動名稱</th>
      <th>活動票券id</th>
      <th>票券種類</th>
      <th>數量</th>
      <th>票價</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @ticket_types.each do |ticket_type| %>
      <tr>
        <td><%= ticket_type.activity.id %></td>
        <td><%= ticket_type.activity.title %></td>
        <td><%= ticket_type.id %></td>
        <td><%= ticket_type.title %></td>
        <td><%= ticket_type.quantity %></td>
        <td>＄<%= ticket_type.price %></td>
        <td>
          <%= link_to "編輯", edit_activity_path(ticket_type.activity_id), class: 'button is-light is-small' %>
          <%= link_to "刪除", activity_ticket_type_path(id: ticket_type), method: 'delete', data: { confirm: '確認刪除?!' } %>
          <%# <% byebug %>
        </td>     
      </tr> 
    <% end %>
  </tbody>
</table>