Desktop/ruby_tix-dev/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, 
             :controllers => {
               :registrations => "users/registrations", 
               :omniauth_callbacks => "users/omniauth_callbacks"
             }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :pages do
    # 沒id
    collection do
      get :search
      get :footer_page
    end
  end 


  resources :activities
  root to: 'pages#index'

  resources :orders, only:[:index, :show, :create, :destroy]

  resource :cart, only:[:index, :destroy] do
    collection do
      post :add, path:'add/:id'
    end
  end

  resources :activities, only:[] do
    # 主辦方設定票券寫在activity new 頁面 暫定
    resources :ticket_types, :except => [ :show]
    get "/ticket_types/choose_ticket", to: "ticket_types#choose_ticket"

    # 單一活動底下 comment
    resources :comments, only:[:new, :create, :delete]
  end

  #使用者選則票券頁面
  resources :ticket_types, only:[ :choose_ticket]
  # 訂單成立後顯示個人票券
  resources :tickets, only: [:show]
  
end

Desktop/ruby_tix-dev/app/models/activity.rb
class Activity < ApplicationRecord
  has_many :users, through: :activity_users 
  has_many :activity_users
  has_many :comments
  has_many :tickets

  # ticket_type 寫在activity頁面 巢狀表單
  has_many :ticket_types, dependent: :destroy
  accepts_nested_attributes_for :ticket_types, allow_destroy: true

end

Desktop/ruby_tix-dev/app/models/activity_user.rb
class ActivityUser < ApplicationRecord
  belongs_to :user
  belongs_to :activity
end

Desktop/ruby_tix-dev/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Desktop/ruby_tix-dev/app/models/cart.rb
class Cart

end

Desktop/ruby_tix-dev/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :activity
  validates :content, presence: true
end

Desktop/ruby_tix-dev/app/models/order.rb
class Order < ApplicationRecord
  include AASM
  
  aasm column: :state do
    state :pending, initial: true
    state :paid, :refund, :completed

    event :pay do
      transitions from: :pending, to: :paid
      after do
        # 寄發email，已支付款項
      end
    end

    event :refund do
      transitions from: :paid, to: :refunded

      after do
        # 寄發email，已完成退款
      end
    end

    event :compelte do
      transitions from: :paid, to: :completed
    end
  end

end

Desktop/ruby_tix-dev/app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :ticket_type
  belongs_to :order
end

Desktop/ruby_tix-dev/app/models/ticket_type.rb
class TicketType < ApplicationRecord
  validates :price, :title, :quantity, presence: true
  
  belongs_to :activity
  has_many :tickets
end

Desktop/ruby_tix-dev/app/models/user.rb
class User < ApplicationRecord
  has_many :activities, through: :activity_users
  has_many :activity_users
  has_many :comments

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook, :google_oauth2]

  has_rich_text :content



  def self.from_omniauth(auth)
     # Case 1: Find existing user by facebook uid
     user = User.find_by_fb_uid( auth.uid )
     if user
        user.fb_token = auth.credentials.token
        #user.fb_raw_data = auth
        user.save!
       return user
     end

     # Case 2: Find existing user by email
     existing_user = User.find_by_email( auth.info.email )
     if existing_user
       existing_user.fb_uid = auth.uid
       existing_user.fb_token = auth.credentials.token
       #existing_user.fb_raw_data = auth
       existing_user.save!
       return existing_user
     end

     # Case 3: Create new password
     user = User.new
     user.fb_uid = auth.uid
     user.fb_token = auth.credentials.token
     user.email = auth.info.email
     user.password = Devise.friendly_token[0,20]
     #user.fb_raw_data = auth
     user.save!
     return user
   end




  # where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
  #   user.email = auth.info.email
  #   user.password = Devise.friendly_token[0, 20]
  #   # user.name = auth.info.name
  #   # user.avatar = auth.info.image
  #   # If you are using confirmable and the provider(s) you use validate emails, 
  #   # uncomment the line below to skip the confirmation emails.
  #   # user.skip_confirmation!
  # end
  
end

Desktop/ruby_tix-dev/app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def index
    @activities = Activity.all
  end

  def new
    @activity = Activity.new
    2.times { @activity.ticket_types.build }
  end

  def edit
    @activity= Activity.find(params[:id])
  end

  def update
    @activity= Activity.find(params[:id])
    
    if @activity.update(activity_params)
      redirect_to activity_ticket_types_path(@activity)      
    else
      render :edit
    end
  end

  def create
    @activity = Activity.new(activity_params)
    if @activity.save
      redirect_to activity_ticket_types_path(@activity.id)
    else
      
    end
  end

  def show
    @activity = Activity.find(params[:id])
    @comment= @activity.comments.new
    @comments = @story.comments.order(id: :desc)
  end


  private
  def activity_params
    params.require(:activity).permit(:begin_datetime, :finish_datetime, ticket_types_attributes: [:id, :title, :content, :quantity, :sell_start, :sell_deadline,:price, :_destroy])
  end
end

Desktop/ruby_tix-dev/app/controllers/carts_controller.rb
class CartsController < ApplicationController
end

Desktop/ruby_tix-dev/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  acts_as_paranoid without_default_scope: true

  def create
    @activity = Avtivity.find(parmas[:id])  
    @comment = @activity.comments.create(comment_params)  
  end

  private
  def comment_params
    params.require(:comment).permit(:content)
  end
end

Desktop/ruby_tix-dev/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  
end

Desktop/ruby_tix-dev/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # before_action :authenticate_user!
  def index
  end

  def footer_page
  end

  def search
    p params[:search]
    # ILIKE & LIKE
    # limit(2) -> 搜尋前兩個
    @search_value = User.where('email ILIKE ?', "%#{params[:search]}%").limit(2)
    respond_to do |format|
      format.json {render json: @search_value}
    end
  end
end

Desktop/ruby_tix-dev/app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  
  # 顯示使用者票券
  def show
    @ticket = Ticket.find(params[:id])
    owner_id = @ticket.order.user_id
    @ticket_owner= User.find(owner_id)
  end
end

Desktop/ruby_tix-dev/app/controllers/users_controller.rb
class UsersController < Devise::RegistrationsController

  def index
    redirect_to root_path
  end
end

Desktop/ruby_tix-dev/app/helpers/activities_helper.rb
module ActivitiesHelper
end

Desktop/ruby_tix-dev/app/helpers/application_helper.rb
module ApplicationHelper
end

Desktop/ruby_tix-dev/app/helpers/comments_helper.rb
module CommentsHelper
end

Desktop/ruby_tix-dev/app/helpers/pages_helper.rb
module PagesHelper
end

Desktop/ruby_tix-dev/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyTix</title>
      
  
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="w-full relative min-h-full	">
      <section class="max-w-screen-xl  m-auto">
        <%= render 'shared/navbar' %>
      </section>

      <section class="max-w-screen-xl  m-auto">
        <%= render 'shared/mainbar' %>
      </section>

      <section class="max-w-screen-xl  m-auto">
        <%= render 'shared/option' %>
      </section>


      <section class="max-w-screen-xl  m-auto bg-gray-300	">
        <%= yield %>
      </section>

      <section class="max-w-screen-xl  m-auto bottom-0">
        <%= render 'shared/footer' %>
      </section>

      <section class="max-w-screen-xl  m-auto ">
        <%= render 'shared/float' %>
      </section>

    </div>
  </body>
</html>

Desktop/ruby_tix-dev/app/views/pages/footer_page/_questions.html.erb
<h3>questions</h3>

Desktop/ruby_tix-dev/app/views/shared/_float.html.erb
<div class="bg-yellow-400 fixed bottom-0 right-0 mr-24 mb-16 border-red-600 js-chatbox hidden">
  
  <div class="flex justify-between m-1">
    <div>
      <p class="text-xl">RUBYTIX</p>
    </div>
    <div class="js-close-btn">
      <i class="far fa-window-close fa-2x"></i>
    </div>
  </div>

  <div class="bg-yellow-100 h-40 w-40">
    <p>Hello!</p>
  </div>

  <div class="bg-yellow-300 h-10 w-40 flex justify-around items-center">
    <div class="bg-yellow-400">aaaaa</div>
    <div class="bg-yellow-400">bbbbb</div>
    <div class="bg-yellow-400">ccccc</div>
  </div>
</div>


<div class="fixed bottom-0 right-0 m-3">

  <div class="rounded-full h-12 w-12 flex items-center justify-center bg-red-300 js-chat-btn">
    <i class="far fa-comment-dots fa-2x"></i> 
  </div>
  

  <a href="#">
    <div class="rounded-full h-12 w-12 flex items-center justify-center bg-red-300 mt-1">
      <i class="fas fa-arrow-up fa-2x"></i>  
    </div>
  </a>

</div>

Desktop/ruby_tix-dev/app/views/shared/_footer.html.erb
<section class="flex bg-red-200 justify-between px-3 text-center bg-yellow-600">
  <div class="flex-wrap  justify-center text-left">
    <li class="list-none justify-center">
      <%= link_to root_path do%>
        <%= image_tag '/images/newlogo.png' ,class:"h-20" %>
      <% end%>
    </li>
    <li  class="list-none justify-center ml-3"> 
      <i class="far fa-envelope"></i> contact@rubytix.fun
    </li>
    <li class="list-none justify-center ml-3">
      <i class="far fa-clock"></i>週一至週五(10:00~17:00)
    </li>
  </div>

  <div class="flex-wrap  justify-center py-3">
    <li class="list-none text-xl font-bold">參加活動</li>
    <li class="list-none justify-center mt-2">
      <%= link_to '購票須知', footer_page_pages_path  , class: "hover:no-underline hover:text-gray-100" %>
    </li>
    <li class="list-none justify-center">
      <%= link_to '常見問題', "/footer_page/_questions.html.erb", class: "hover:no-underline hover:text-gray-100" %>     
    </li>
  </div>

  <div class="flex-wrap  justify-center py-3">
    <li class="list-none text-xl font-bold">辦理活動</li>
    <li class="list-none justify-center mt-2">
      <%= link_to '辦理流程', "/footer_page/_process.html.erb", class: "hover:no-underline hover:text-gray-100" %>     
    </li>
    <li class="list-none justify-center">
      <%= link_to '售票須知', "/footer_page/_sell_purchase.html.erb", class: "hover:no-underline hover:text-gray-100" %>     
    </li>
    <li class="list-none justify-center">
      <%= link_to '常見問題', "/footer_page/_questions.html.erb", class: "hover:no-underline hover:text-gray-100" %>     
    </li>
  </div>
  
  <div class="flex-wrap  justify-center py-3">
    <li class="list-none text-xl font-bold">聯絡我們</li>
    <li class="list-none justify-center  mt-2">
      <%= link_to '認識我們', "/footer_page/_about_us.html.erb", class: "hover:no-underline hover:text-gray-100" %>     
    </li>
    <li class="list-none justify-center">
      <%= link_to '客服中心', "/footer_page/_service_centre.html.erb", class: "hover:no-underline hover:text-gray-100" %>     
    </li>
    <li class="list-none justify-center">
      <%= link_to '服務條款', "/footer_page/_service_terms.html.erb", class: "hover:no-underline hover:text-gray-100" %>     
    </li>
  </div>
</section>

<section class="text-center bg-black text-gray-500 py-2">
  <p>&copy; 2020 rubytix.fun<p>
</section>

Desktop/ruby_tix-dev/app/views/shared/_mainbar.html.erb
<div class=" w-full h-20 fixed max-w-screen-xl mt-20 z-20">



<section class="bg-gray-900	 flex justify-around py-3 ">

    <button>
      <%= link_to '熱門精選', root_path,  class: "text-yellow-600 mx-7 text-xl font-bold  hover:no-underline hover:text-gray-100" %> 
    </button>

    <button>
      <%= link_to '特色活動',  '#', class: "text-yellow-600 mx-7 text-xl font-bold hover:no-underline hover:text-gray-100" %> 
    </button>

    <button>
      <%= link_to '5xRuby',  '#', class: "text-yellow-600 mx-7 text-xl font-bold hover:no-underline hover:text-gray-100" %> 
    </button>

    <button>
      <%= link_to '休閒娛樂', '#', class: "text-yellow-600 mx-7 text-xl font-bold hover:no-underline hover:text-gray-100" %> 
    </button>

    <button>
      <%= link_to '資訊科技', '#', class: "text-yellow-600 mx-7 text-xl font-bold hover:no-underline hover:text-gray-100" %> 
    </button>
</section>

</div>

Desktop/ruby_tix-dev/app/views/shared/_navbar.html.erb
<div class=" w-full h-20 fixed max-w-screen-xl z-20">


  <% if current_user %>


  <section class="bg-red-700 flex justify-between px-3 items-center">
    <section>
      <%= link_to root_path do%>
        <%= image_tag '/images/newlogo.png' ,class:"h-20" %>
      <% end%>
    </section>

    <div class="search-bar flex">
      <input type="text" class="search-input bg-red-100 rounded-md h-10 mx-3" placeholder="11">
      <button class="submit search-btn flex items-center justify-center px-4 py-2 border border-transparent rounded-md shadow-sm text-base font-medium text-gray-100 bg-red-600 hover:bg-gray-900 hover:text-yellow-600 h-10">搜尋</button>
    </div>

    <section class="flex">
      <select name="current_user_account_name" class="current_user_account_name rounded-md mx-3 px-96">
        <option value="1"  selected="selected"><%= current_user.account_name %></option>
        <option value="2" class="member_centre">會員中心</option>
        <option value="3" class="activitv y_record">活動紀錄</option>
        <option value="4" class="hold_activity">舉辦活動</option>
        <option value="5" class="shopping_cart">購物車</option>

      </select>

      <button class="submit search-btn flex items-center justify-center px-4 py-2 border border-transparent rounded-md shadow-sm text-base font-medium text-gray-100 bg-red-600 hover:bg-gray-900 hover:text-yellow-600 hover:no-underline h-10">
        <%= link_to('登出', destroy_user_session_path, :method => :delete) %> 
        
      </button>

      
    </section>


  </section>

          
  <% else %>

  <section class="bg-red-700 flex justify-between px-3 items-center">

    <section>
      <%= link_to root_path do%>
        <%= image_tag '/images/newlogo.png' ,class:"h-20" %>
      <% end%>
    </section>

    <div class="search-bar flex">
      <input type="text" class="search-input bg-red-100 rounded-md h-10 mx-3" placeholder="11">
      <button class="submit search-btn flex items-center justify-center px-4 py-2 border border-transparent rounded-md shadow-sm text-base font-medium text-gray-100 bg-red-600 hover:bg-gray-900 hover:text-yellow-600 h-10">搜尋</button>
    </div>

    <div class="flex">
      <button class="submit search-btn flex items-center justify-center px-4 py-2 border border-transparent rounded-md shadow-sm text-base font-medium text-gray-100 bg-red-600 hover:bg-gray-900 hover:text-yellow-600 hover:no-underline h-10 mx-3">
        <%= link_to('會員註冊', new_registration_path(:user)) %> 
      </button>

      <button class="submit search-btn flex items-center justify-center px-4 py-2 border border-transparent rounded-md shadow-sm text-base font-medium text-gray-100 bg-red-600 hover:bg-gray-900 hover:text-yellow-600 hover:no-underline h-10">
        <%= link_to('會員登入', new_session_path(:user))%>
      </button>
    </div>
  </section>




  <% end %>
</div>








<script>
  document.addEventListener('DOMContentLoaded', function(){

    const searchBtn = document.querySelector('.search-btn')

    searchBtn.addEventListener('click', function() {
      const searchInput = document.querySelector('.search-input').value
      console.log(searchInput);
      const searchAPI = window.location.origin
      fetch(`${searchAPI}/pages/search.json?search=${searchInput}`)
      // response.json可將得到的結果轉換成json格式
      .then(response => response.json())
      .then(result => console.log(result))
      
      ;
    })
  })


</script>

Desktop/ruby_tix-dev/app/views/shared/_notice.html.erb
<div class="notification is-info is-marginless">
  <button class="delete"></button>
  <i class="far fa-comment-dots "></i>&nbsp; <%= notice%>
</div>

Desktop/ruby_tix-dev/app/views/shared/_option.html.erb
<% if current_user  %>

<section class="bg-red-500">

  <section class="centre mx-8" style="display: none;">
    <button>
      <%= link_to '編輯會員資料', edit_registration_path(:user), class: "mx-8" %> 
    </button>

    <button>
      <%= link_to '會員權益',  '#',  class: "mx-8" %> 
    </button>

    <button>
      <%= link_to '服務條款', '#', class: "mx-8" %> 
    </button>
  
  </section>

  <section class="record mx-8" style="display: none;">
    <button>
      <%= link_to '已收藏的活動',  '#', class: "mx-8" %> 
    </button>

    <button>
      <%= link_to '參加過的活動', '#', class: "mx-8" %> 
    </button>

    <button>
      <%= link_to '評價過的活動', '#', class: "mx-8" %> 
    </button>
  
  </section>

  <section class="hold mx-8" style="display: none;">
    <button>
      <%= link_to '辦理新活動', '#', class: "mx-8" %> 
    </button>

    <button>
      <%= link_to '辦理中的活動',  '#', class: "mx-8" %> 
    </button>

    <button>
      <%= link_to '已辦理的活動',  '#', class: "mx-8" %> 
    </button>
  
  </section>

  <section class="cart mx-8" style="display: none;">
  </section>
</section>
        
<% else %>



<% end %>