Desktop/ruby_tix-dev/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, 
             :controllers => {
               :registrations => "users/registrations", 
               :omniauth_callbacks => "users/omniauth_callbacks"
             }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :pages do
    # 沒id
    collection do
      get :search
      get :footer_page
    end
  end 


  resources :activities
  root to: 'pages#index'

  resources :orders, only:[:index, :show, :create, :destroy]

  resource :cart, only:[:index, :destroy] do
    collection do
      post :add, path:'add/:id'
    end
  end

  resources :activities, only:[] do
    # 主辦方設定票券寫在activity new 頁面 暫定
    resources :ticket_types, :except => [ :show]
    get "/ticket_types/choose_ticket", to: "ticket_types#choose_ticket"

    # 單一活動底下 comment
    resources :comments, only:[:new, :create, :delete]
  end

  #使用者選則票券頁面
  resources :ticket_types, only:[ :choose_ticket]
  # 訂單成立後顯示個人票券
  resources :tickets, only: [:show]
  
end

Desktop/ruby_tix-dev/app/models/activity.rb
class Activity < ApplicationRecord
  has_many :users, through: :activity_users 
  has_many :activity_users
  has_many :comments
  has_many :tickets

  # ticket_type 寫在activity頁面 巢狀表單
  has_many :ticket_types, dependent: :destroy
  accepts_nested_attributes_for :ticket_types, allow_destroy: true

end

Desktop/ruby_tix-dev/app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def index
    @activities = Activity.all
  end

  def new
    @activity = Activity.new
    2.times { @activity.ticket_types.build }
  end

  def edit
    @activity= Activity.find(params[:id])
  end

  def update
    @activity= Activity.find(params[:id])
    
    if @activity.update(activity_params)
      redirect_to activity_ticket_types_path(@activity)      
    else
      render :edit
    end
  end

  def create
    @activity = Activity.new(activity_params)
    if @activity.save
      redirect_to activity_ticket_types_path(@activity.id)
    else
      
    end
  end

  def show
    @activity = Activity.find(params[:id])
    @comment= @activity.comments.new
    @comments = @story.comments.order(id: :desc)
  end


  private
  def activity_params
    params.require(:activity).permit(:begin_datetime, :finish_datetime, ticket_types_attributes: [:id, :title, :content, :quantity, :sell_start, :sell_deadline,:price, :_destroy])
  end
end

Desktop/ruby_tix-dev/app/helpers/activities_helper.rb
module ActivitiesHelper
end

Desktop/ruby_tix-dev/app/views/activities/_activity_form.html.erb
<%= form_for @activity do |f|%>






    
    
    <%# ticket_types nested form %>
    <div class="nested-container">
      <div class="nested-foorm-header">
        <div>票券名稱</div>
        <div>數量</div>
        <div>價格</div>
        <div>操作</div>
      </div>

      <div data-controller="ticket-types-form" class="nested-form">
        <template data-ticket-types-form-target="form">
          <%= f.fields_for :ticket_types, TicketType.new, child_index: 'NEW_FORM' do |new_form|%>  
            <%= render 'ticket_types_form', form: new_form %>
          <% end %>
        </template>

          <%# current form %>
        <%= f.fields_for :ticket_types do |form|%>  
          <%= render 'ticket_types_form', form: form %>
        <% end %>



        <div data-action = "click->ticket-types-form#addTicketType" data-ticket-types-form-target="addBtn" class="nested-add-btn">
          <%= link_to '#' do %>
            <i class="fas fa-plus-circle"></i>新增票種
          <% end %>
        </div>

        <%# <div >
          <a href="＃"><i class="fas fa-plus-circle"></i>免費票</a>
        </div> %>
      </div>
    </div>


    <%# ticket_types form end %>
  

  <%= f.submit '送出' %>
  <% end %>

Desktop/ruby_tix-dev/app/views/activities/_ticket_types_form.html.erb
          <div class="ticketType-form" id="accordion" new-ticket_types ="<%= form.object.new_record? %>" >
            <div class="nested-basic-info">
              <%= form.text_field:title%>
              <%= form.number_field:quantity, placeholder: '數量', min: 0 %>
              <%= form.number_field:price, placeholder: '票價', min:0 %>


              <%#= link_to '#', class:"card-link", data:{toggle:"collapse"},cdata:{parent:"#accordion"} do %>
                <%# <i class="fas fa-chevron-circle-down"></i> %>
              <%# end %>

              <%= link_to '#', data: { action: 'ticket-types-form#removeTicketType' } do %>
                <i class="far fa-trash-alt new-ticket-delete-btn"></i>
              <% end %>
            </div>


            <div class=" nested-hidden-info"  >
              <div class="card card-body collapse.show" id="e">
                <div>
                  <%= form.label:sell_start, '售票開始日'%>
                </div>

                <div>
                  <%= form.date_field:sell_start %>
                  <%= form.time_field:sell_start %>
                </div>

                <div>
                  <%= form.label:finish_datetime, '結束時間' %>
                </div>

                <div>
                  <%= form.date_field:sell_deadline %>
                  <%= form.time_field:sell_deadline %>
                </div>

                <%= form.label:content, '票券說明'%>
                <%= form.text_area:content, rows: "5" %>
              </div>
            </div>

            <%= form.hidden_field :_destroy %>

          </div>

Desktop/ruby_tix-dev/app/views/activities/edit.html.erb
<h2>編輯活動票券</h2>
<%= render 'activity_form', activity: @activity %>

Desktop/ruby_tix-dev/app/views/activities/index.html.erb
<h1>活動列表</h1>
請選擇想參與的活動

<%= link_to "新增活動", new_activity_path %>

<table>
  <thead>
    <tr>
      <td>活動id</td>
      <td>活動名稱</td>
      <td>活動內容</td>
      <td>主辦單位</td>
      <td>活動狀態</td>  <%# <尚未開始/進行中/已結束 %>
      <td>開始時間</td>
      <td>結束時間</td>
      <td>活動地點</td>
      <td>購買狀態</td>    <%# 我想參加！/可參加時告訴我 %>
      <td></td>
    </tr>
  </thead>
  
  <tbody>
    <% @activities.each do |activity| %>
    <tr>
      <td><%= activity.id %></td>
      <td> <%= activity.title %> </td>
      <td> <%= activity.content  %> </td>
      <td> <%= activity.user_id  %> </td>
      <td> <%= activity.is_available  %> </td>
      <td> <%= activity.begin_datetime  %> </td>
      <td> <%= activity.finish_datetime  %> </td>
      <td> <%= activity.location  %> </td>
      <td> <%= activity.buy  %> </td>
      <td>
        <% if activity.ticket_types != [] %>
          <%= link_to '票券種類', activity_ticket_types_path(activity) %>
        <% else %>
          <%= link_to '新增票券', edit_activity_path(activity)%>
        <% end %>
      </td>
    </tr>   
    <%end %>
  </tbody>
</table> 

Desktop/ruby_tix-dev/app/views/activities/new.html.erb
<h2>新增活動</h2>
<%= render 'activity_form', activity: @activity %>

Desktop/ruby_tix-dev/app/views/activities/show.html.erb
<h1>五倍電影節</h1>  <%# 暫定  for testig comment view only %>
<%= render 'comments/comments', activity:@activity %>